### PR TITLE
Add config values for prefix and suffix for nether and end.

### PR DESCRIPTION
**Pull request by benwoo1110**
It was kinda weird... prefix and suffix for nether and end setting not even in the config and there is code to load those values from config....?

I think its a good option to add to config anyways, so did as such.

### CODE REVIEW

**Comment by nicegamer7** [comment]
Could you separate the spelling mistakes into a new commit? Would make the diff a little easier to read.

I'm talking about `NETEHR_PORTALS_CONFIG` and `MVNPconfiguration`.

**Comment by benwoo1110** [comment]
you are right, or we can just quickly make a PR to fix the spelling errors and merge it first. so we don't have to deal with merge conflict of other prs as well.

**Comment by nicegamer7** [comment]
Sure, sounds good.

**Comment by benwoo1110** [comment]
@nicegamer7  #206

**Comment by benwoo1110** [comment]
I think I will manually rebase this, too many merge conflicts lolll

**Review by nicegamer7 — APPROVED** [review]
Looks good, did you test this?

**Comment by benwoo1110** [comment]
Yea, but that was 2 months back, will test it now.

**Comment by benwoo1110** [comment]
Ok, tested and it does work. Here is how the config looks: https://j.mp/36TLHGv

In-game test when nether suffix is changed to `-NETHER`:
image

image

```
[10:59:59 INFO]: [Multiverse-Core-Debug] TravelAgent not available for PlayerPortalEvent for Benji_0224
[10:59:59 INFO]: [Multiverse-Core-Debug] Got teleport event for player 'Benji_0224' with cause 'NETHER_PORTAL'
[10:59:59 INFO]: [Multiverse-Core-Debug] Inferred sender 'null' from name 'null', fetched from name 'Benji_0224'
[10:59:59 INFO]: [Multiverse-Core-Debug] Player 'Benji_0224' was allowed to go to 'world-NETHER' because enforceaccess is off.
[10:59:59 INFO]: [Multiverse-Core-Debug] MV-Core is allowing Player 'Benji_0224' to go to 'world-NETHER'.
[10:59:59 INFO]: [Multiverse-Core-Debug] Handling gamemode for player: Benji_0224, Changing to SURVIVAL
[11:00:03 INFO]: Benji_0224 issued server command: /mv info
[11:00:03 INFO]: [Multiverse-Core-Debug] Checking to see if player [Benji_0224] has permission [multiverse.core.info]... YES
```

I think it can be merged

**Comment by nicegamer7** [comment]
Okay, looks good.

**Pull request merged**
