### PR TITLE
Fix some code typos.

### PR DESCRIPTION
**Pull request by benwoo1110**

### CODE REVIEW

**Review by nicegamer7 — APPROVED** [review]
LGTM.

**Comment by benwoo1110** [comment]
yea, now time for some merge conflicts hahaha

**Comment by nicegamer7** [comment]
@benwoo1110 you missed some `MVNPconfiguration`, lines 129, 130, 140, and 143.

**Comment by benwoo1110** [comment]
oh no, it was due to the previous merge for the bug fix

**Pull request merged**
